#!/usr/bin/env bash
# Install nginx on your web-01
# Nginx should be listening on port 80.
apt-get -y update
apt-get -y install nginx
ufw allow 'NGINX HTTP'
echo 'Hello World' > /var/www/html/index.nginx-debian.html
service nginx start
