#!/usr/bin/env bash
# configure web-02 to be identical to web-01:add a custom Nginx response header

apt-get update
apt-get -y install nginx
sed -ie "s/^server {$/server {\n\tadd_header X-Served-By $170335-web-02;/g" /etc/nginx/sites-available/default
service nginx restart