#!/bin/bash

# Get all active IPv4 addresses
ip_addresses=$(ifconfig | grep 'inet ' | awk '{print $2}' | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')

# Loop through each IP address and print it out
for ip_address in $ip_addresses; do
    echo "$ip_address"
done
