#!/usr/bin/env bash
# get Apache to run on the container and to return a page containing
# Hello Holberton when querying the root of it
docker exec -it 5a294d744195 /etc/init.d/apache2 start
docker exec -it 5a294d744195 /bin/bash
